version: '3.8'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    networks:
      public_bridge:
    volumes:
      - "nexus:/nexus-data"
    labels:
      - "traefik.http.routers.nexus.rule=Host(`nexus.cloudcrafts.club`)"
      - "traefik.http.routers.nexus.tls=true"
      - "traefik.http.routers.nexus.tls.certresolver=cloudflare"
      - "traefik.http.routers.nexus.service=nexus-service"
      - "traefik.http.services.nexus-service.loadBalancer.server.port=8081"
      - "traefik.http.routers.docker-registry.rule=Host(`dckr.cloudcrafts.club`)"
      - "traefik.http.routers.docker-registry.tls=true"
      - "traefik.http.routers.docker-registry.tls.certresolver=cloudflare"
      - "traefik.http.routers.docker-registry.service=docker-registry-service"
      - "traefik.http.services.docker-registry-service.loadBalancer.server.port=5000"

volumes:
  nexus:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/external/nexus

networks:
  public_bridge:
    external: true